site_name: Documentación Software IEC

theme:
  name: material
  palette:
    - scheme: default
      primary: "white"
      accent: "deep orange"
      toggle:
        icon: material/brightness-7
        name: Cambiar al modo oscuro

    - scheme: slate
      primary: "white"
      accent: "deep orange"
      toggle:
        icon: material/brightness-4
        name: Cambiar al modo claro
  language: es
  logo: images/logo_iec.png
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
  icon:
    annotation: material/arrow-right-circle

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - 1️⃣ curva3d:
      - Inicio: curva3d/index.md

  - 2️⃣ dxftoedb:
      - Introducción: dxftoedb/introduccion.md
      - Instalación: dxftoedb/instalacion.md
      - Prepinchado: dxftoedb/prepinchado.md
      - Configuración: dxftoedb/configuracion.md
      - Dxftoedb1:
          - Dxftoedb1: dxftoedb/dxftoedb1.md
          - Planos Grilla: dxftoedb/planos_grilla.md
          - Grilla Excel: dxftoedb/grilla_excel.md
      - Dxftoedb2: dxftoedb/dxftoedb2.md
      - Dxftoedb3: dxftoedb/dxftoedb3.md
      - Dxftoedb4: dxftoedb/dxftoedb4.md
      - Problemas Frecuentes: dxftoedb/problemas.md
      - Ideas: dxftoedb/ideas.md

  - 3️⃣ etabs_sdk:
      - Inicio: etabs_sdk/index.md

  - Comandos Autocad: comandos-autocad.md
# http://127.0.0.1:8000/dxftoedb/dxftoedb1/planos_grilla.md
# http://127.0.0.1:8000/dxftoedb/planos_grilla/
