site_name: Documentaci贸n Software IEC
site_url: https://iec-ingenieria.github.io/documentacion/

theme:
  name: material
  palette:
    - scheme: default
      primary: "white"
      accent: "deep orange"
      toggle:
        icon: material/brightness-7
        name: Cambiar al modo oscuro

    - scheme: slate
      primary: "white"
      accent: "deep orange"
      toggle:
        icon: material/brightness-4
        name: Cambiar al modo claro
  language: es
  logo: images/logo_iec.png
  favicon: images/logo_iec.png
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    # - navigation.sections
    # - navigation.expand
    - navigation.path
    - navigation.top
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - navigation.tabs.sticky
    - navigation.footer
  icon:
    annotation: material/arrow-right-circle
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://cl.linkedin.com/company/iec-ingenier-a-s.a.
    - icon: fontawesome/brands/github
      link: https://github.com/iec-ingenieria
    - icon: fontawesome/solid/paper-plane
      link: mailto:<iec@iec.cl>

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  -  Inicio: index.md

  -  Instalaci贸n: instalacion.md

  - 1锔 dxftoedb:
      - Introducci贸n: dxftoedb/introduccion.md
      - Prepinchado: dxftoedb/prepinchado.md
      - Configuraci贸n: dxftoedb/configuracion.md
      - Dxftoedb1:
          - Dxftoedb1: dxftoedb/dxftoedb1.md
          - Planos Grilla: dxftoedb/planos_grilla.md
          - Grilla Excel: dxftoedb/grilla_excel.md
      - Dxftoedb2: dxftoedb/dxftoedb2.md
      - Dxftoedb3: dxftoedb/dxftoedb3.md
      - Dxftoedb4: dxftoedb/dxftoedb4.md
      - Problemas Frecuentes: dxftoedb/problemas.md
      - Ideas: dxftoedb/ideas.md
      - Versiones: dxftoedb/versiones.md

  - 2锔 edbtopre:
      - Introducci贸n: edbtopre/introduccion.md
      - Input: edbtopre/input.md
      - Output: edbtopre/output.md
      - Versiones: edbtopre/versiones.md

  - 3锔 pretovh:
      - Introducci贸n: pretovh/introduccion.md
      - Input: pretovh/input.md
      - Output: pretovh/output.md
      - Versiones: pretovh/versiones.md

  -  Comandos Autocad: comandos-autocad.md
  -  Directorios: directorios.md
